GET http://localhost:5000/subscribers

###
GET http://localhost:5000/subscribers/64be0e3c79b9032d144127b6

###
POST http://localhost:5000/subscribers
Content-Type: application/json

{
    "name":"Abhimanyu",
    "subscribedToChannel":"web dev"
}


### 
DELETE  http://localhost:5000/subscribers/64be0e3c79b9032d144127b6

###
PATCH  http://localhost:5000/subscribers/64be0e3c79b9032d144127b6
Content-Type: application/json

{
    "name":"Harry",
    "subscribedToChannel":"code with harry"
}